### PR TITLE
Feature/french translation

### PR DESCRIPTION
**Pull request by fullstackninja864**
- Add french transalations for defi-app.

Submitted by @huguesk

Refer to issue #10

### CODE REVIEW

**Comment by uzyn** [comment]
Thanks @huguesk. We will need French-speaking member to vouch for the translation.

**Comment by huguesk** [comment]
@uzyn @fullstackninja864 @monstrobishi, just saw that you already took care of everything, thank you very much for this! :) 
As requested, hier is my DFI address: dYFDD26hu2LtCrzGyVLzGoXBQGkLX38CwU
Keep up the good work, you guys rock!

**Comment by huguesk** [comment]
@uzyn @fullstackninja864 @monstrobishi, just saw that you already took care of everything, thank you very much for this! :) 
As requested, hier is my DFI address: dYFDD26hu2LtCrzGyVLzGoXBQGkLX38CwU
Keep up the good work, you guys rock!

**Comment by uzyn** [comment]
Thanks for your contribution @huguesk . 150 DFI has been transferred from community fund. 
txid: [7c896510a6450496ef70e11a6caa05c2f95e148a629543f8161f187cd37cadc9](https://explorer.defichain.io/#/DFI/mainnet/tx/7c896510a6450496ef70e11a6caa05c2f95e148a629543f8161f187cd37cadc9)

**Pull request merged**
